export const auditorData = [
  {
    id: 0,
    name: "Iva Key",
    status: "deleted",
    userName: "Burton",
    company: "STEELTAB",
  },
  {
    id: 1,
    name: "Stout Strickland",
    status: "deleted",
    userName: "Mathis",
    company: "KOG",
  },
  {
    id: 2,
    name: "Mcleod Marks",
    status: "deleted",
    userName: "Leola",
    company: "MAGNINA",
  },
  {
    id: 3,
    name: "Rosa Waller",
    status: "deleted",
    userName: "Cooper",
    company: "COMTRACT",
  },
  {
    id: 4,
    name: "Blair Dejesus",
    status: "deleted",
    userName: "Ross",
    company: "FLUMBO",
  },
  {
    id: 5,
    name: "Bentley Melton",
    status: "deleted",
    userName: "Mercer",
    company: "XYLAR",
  },
  {
    id: 6,
    name: "Keller Mathis",
    status: "deleted",
    userName: "Sullivan",
    company: "EQUITAX",
  },
  {
    id: 7,
    name: "Bishop Mcclain",
    status: "active",
    userName: "Felicia",
    company: "SPRINGBEE",
  },
  {
    id: 8,
    name: "Sheppard Watkins",
    status: "active",
    userName: "Whitney",
    company: "XERONK",
  },
  {
    id: 9,
    name: "Nellie Browning",
    status: "active",
    userName: "Harriett",
    company: "DIGIFAD",
  },
  {
    id: 10,
    name: "Marta Underwood",
    status: "active",
    userName: "Diane",
    company: "ISOSPHERE",
  },
  {
    id: 11,
    name: "Coffey Patton",
    status: "active",
    userName: "Eva",
    company: "TALAE",
  },
  {
    id: 12,
    name: "Margie Sargent",
    status: "active",
    userName: "Terra",
    company: "ZORROMOP",
  },
  {
    id: 13,
    name: "Kirk Long",
    status: "active",
    userName: "Burgess",
    company: "ORGANICA",
  },
  {
    id: 14,
    name: "Buchanan Coffey",
    status: "active",
    userName: "Shaw",
    company: "IRACK",
  },
  {
    id: 15,
    name: "Elena Garcia",
    status: "active",
    userName: "Patti",
    company: "PURIA",
  },
  {
    id: 16,
    name: "Tammie Pollard",
    status: "active",
    userName: "Mercado",
    company: "SENMAO",
  },
  {
    id: 17,
    name: "Jan Oliver",
    status: "active",
    userName: "Neva",
    company: "BESTO",
  },
  {
    id: 18,
    name: "Humphrey Perez",
    status: "active",
    userName: "Alejandra",
    company: "NIXELT",
  },
  {
    id: 19,
    name: "Beck Murray",
    status: "active",
    userName: "Sherry",
    company: "VERTIDE",
  },
  {
    id: 20,
    name: "Brigitte Watson",
    status: "active",
    userName: "Compton",
    company: "EXOSPEED",
  },
  {
    id: 21,
    name: "Estes Thornton",
    status: "active",
    userName: "Bradley",
    company: "IMKAN",
  },
  {
    id: 22,
    name: "Marisol Sharp",
    status: "deleted",
    userName: "Richardson",
    company: "DECRATEX",
  },
  {
    id: 23,
    name: "Ebony Cantu",
    status: "deleted",
    userName: "Oneill",
    company: "NAVIR",
  },
  {
    id: 24,
    name: "Sykes Barnett",
    status: "deleted",
    userName: "Mclaughlin",
    company: "IMAGEFLOW",
  },
  {
    id: 25,
    name: "Ava Franklin",
    status: "deleted",
    userName: "Adrian",
    company: "PEARLESSA",
  },
  {
    id: 26,
    name: "Heather Reynolds",
    status: "deleted",
    userName: "Ladonna",
    company: "ENTROPIX",
  },
  {
    id: 27,
    name: "Barrett Horn",
    status: "deleted",
    userName: "Faye",
    company: "DUFLEX",
  },
  {
    id: 28,
    name: "Pitts Howe",
    status: "active",
    userName: "Tammi",
    company: "ISOLOGICS",
  },
  {
    id: 29,
    name: "Katy Buckner",
    status: "active",
    userName: "Turner",
    company: "BRAINCLIP",
  },
];
export const questionData = [
  {
    id: 0,
    name: "Tammi Taylor",
    company: "SUPPORTAL",
  },
  {
    id: 1,
    name: "Mills Hunter",
    company: "BALUBA",
  },
  {
    id: 2,
    name: "Jordan Hobbs",
    company: "CONFRENZY",
  },
  {
    id: 3,
    name: "Buck Mckay",
    company: "ZOLAVO",
  },
  {
    id: 4,
    name: "Rhonda Coffey",
    company: "AMTAP",
  },
  {
    id: 5,
    name: "Dorothy Hardin",
    company: "CYTRAK",
  },
  {
    id: 6,
    name: "Baker Alexander",
    company: "EVEREST",
  },
  {
    id: 7,
    name: "Hays Haley",
    company: "IMPERIUM",
  },
  {
    id: 8,
    name: "Maxwell Doyle",
    company: "PYRAMI",
  },
  {
    id: 9,
    name: "Sparks Rice",
    company: "QUILCH",
  },
  {
    id: 10,
    name: "Earnestine Cunningham",
    company: "SONIQUE",
  },
  {
    id: 11,
    name: "Young Sweeney",
    company: "PASTURIA",
  },
  {
    id: 12,
    name: "Shari Walker",
    company: "GEEKFARM",
  },
  {
    id: 13,
    name: "Maryann Fry",
    company: "DIGINETIC",
  },
  {
    id: 14,
    name: "Gale Patton",
    company: "ULTRASURE",
  },
  {
    id: 15,
    name: "Howell Petty",
    company: "VIDTO",
  },
  {
    id: 16,
    name: "Berger Marshall",
    company: "APPLIDECK",
  },
  {
    id: 17,
    name: "Gladys Carr",
    company: "BLANET",
  },
  {
    id: 18,
    name: "Chasity Calhoun",
    company: "HATOLOGY",
  },
  {
    id: 19,
    name: "Faith Mcbride",
    company: "POSHOME",
  },
  {
    id: 20,
    name: "Nadine Burns",
    company: "OPTICALL",
  },
  {
    id: 21,
    name: "Rios Shepard",
    company: "ZILLADYNE",
  },
  {
    id: 22,
    name: "Millie David",
    company: "EXOVENT",
  },
  {
    id: 23,
    name: "Page Barron",
    company: "AVIT",
  },
  {
    id: 24,
    name: "Obrien Fields",
    company: "EURON",
  },
  {
    id: 25,
    name: "Margaret Wiggins",
    company: "BALOOBA",
  },
  {
    id: 26,
    name: "Kimberly Booker",
    company: "SATIANCE",
  },
  {
    id: 27,
    name: "Wood Livingston",
    company: "GENEKOM",
  },
  {
    id: 28,
    name: "Roseann Nguyen",
    company: "GEEKULAR",
  },
  {
    id: 29,
    name: "Sheri Joyce",
    company: "ZOID",
  },
];

export const HotelsData = [
  {
    id: 0,
    name: "Jeanine Howell",
    company: "VIDTO",
    timing: "2020-03-07T08:13:04+05:30",
    location: "Cumberland",
    head: "Lorene",
    category: "Poole",
    size: 427,
  },
  {
    id: 1,
    name: "Booth Cleveland",
    company: "ANDERSHUN",
    timing: "2017-06-15T12:19:33+05:30",
    location: "Sidman",
    head: "Nell",
    category: "Pace",
    size: 180,
  },
  {
    id: 2,
    name: "Amalia Ayers",
    company: "COMFIRM",
    timing: "2014-12-08T12:34:37+05:30",
    location: "Dawn",
    head: "Lou",
    category: "Gonzales",
    size: 773,
  },
  {
    id: 3,
    name: "Kramer Pena",
    company: "MITROC",
    timing: "2020-05-28T01:20:39+05:30",
    location: "Edneyville",
    head: "Concepcion",
    category: "Luna",
    size: 730,
  },
  {
    id: 4,
    name: "Deanne Hood",
    company: "MINGA",
    timing: "2014-09-16T06:02:26+05:30",
    location: "Rose",
    head: "Vega",
    category: "Woodard",
    size: 753,
  },
  {
    id: 5,
    name: "Aileen Parker",
    company: "GOLISTIC",
    timing: "2021-12-08T06:06:22+05:30",
    location: "Zeba",
    head: "Della",
    category: "David",
    size: 447,
  },
  {
    id: 6,
    name: "Neal Mccullough",
    company: "SUREPLEX",
    timing: "2017-07-17T07:28:53+05:30",
    location: "Keyport",
    head: "Vickie",
    category: "Stanley",
    size: 103,
  },
  {
    id: 7,
    name: "Page Best",
    company: "VISUALIX",
    timing: "2017-02-01T05:04:01+05:30",
    location: "Bergoo",
    head: "Kelly",
    category: "Kirkland",
    size: 404,
  },
  {
    id: 8,
    name: "Kent Pugh",
    company: "LOCAZONE",
    timing: "2023-03-10T05:03:59+05:30",
    location: "Orviston",
    head: "Clara",
    category: "William",
    size: 252,
  },
  {
    id: 9,
    name: "Lyons Bright",
    company: "FUTURIZE",
    timing: "2018-12-27T01:14:37+05:30",
    location: "Waiohinu",
    head: "Bethany",
    category: "Combs",
    size: 698,
  },
  {
    id: 10,
    name: "Ada Hess",
    company: "ZANITY",
    timing: "2022-03-26T05:21:45+05:30",
    location: "Winston",
    head: "Keisha",
    category: "Holder",
    size: 580,
  },
  {
    id: 11,
    name: "Ursula Pickett",
    company: "ARCHITAX",
    timing: "2019-06-24T12:40:55+05:30",
    location: "Dante",
    head: "Fields",
    category: "Chapman",
    size: 411,
  },
  {
    id: 12,
    name: "Gray Lowe",
    company: "PHUEL",
    timing: "2019-06-14T11:42:55+05:30",
    location: "Germanton",
    head: "Berger",
    category: "Mcleod",
    size: 235,
  },
  {
    id: 13,
    name: "Leigh James",
    company: "CUBIX",
    timing: "2017-02-25T05:04:42+05:30",
    location: "Lowgap",
    head: "Nora",
    category: "Rutledge",
    size: 164,
  },
  {
    id: 14,
    name: "Amparo Flowers",
    company: "CALCULA",
    timing: "2022-07-01T01:48:35+05:30",
    location: "Loveland",
    head: "Ellen",
    category: "Whitaker",
    size: 692,
  },
  {
    id: 15,
    name: "Sweeney Bowman",
    company: "EVENTAGE",
    timing: "2017-08-24T02:21:43+05:30",
    location: "Springville",
    head: "Hawkins",
    category: "Garner",
    size: 744,
  },
  {
    id: 16,
    name: "Bessie Osborn",
    company: "DYMI",
    timing: "2022-06-10T08:22:31+05:30",
    location: "Roderfield",
    head: "Phyllis",
    category: "Osborne",
    size: 796,
  },
  {
    id: 17,
    name: "Andrews Rogers",
    company: "POLARIUM",
    timing: "2022-06-12T03:00:16+05:30",
    location: "Canterwood",
    head: "Beth",
    category: "Perry",
    size: 956,
  },
  {
    id: 18,
    name: "Powers Oliver",
    company: "MAZUDA",
    timing: "2018-04-16T01:45:41+05:30",
    location: "Carlton",
    head: "Gregory",
    category: "Clay",
    size: 612,
  },
  {
    id: 19,
    name: "Chan Butler",
    company: "COMVENE",
    timing: "2016-11-03T04:51:37+05:30",
    location: "Orovada",
    head: "Cheryl",
    category: "Benson",
    size: 477,
  },
  {
    id: 20,
    name: "Hart Bartlett",
    company: "ZANILLA",
    timing: "2014-08-21T08:27:27+05:30",
    location: "Hiko",
    head: "Dorothea",
    category: "Rice",
    size: 927,
  },
  {
    id: 21,
    name: "Hayden Powers",
    company: "IMANT",
    timing: "2021-03-11T12:45:43+05:30",
    location: "Alfarata",
    head: "Dee",
    category: "Rivers",
    size: 617,
  },
  {
    id: 22,
    name: "Melody Dalton",
    company: "GONKLE",
    timing: "2020-01-05T07:14:17+05:30",
    location: "Nelson",
    head: "Martina",
    category: "Fitzpatrick",
    size: 118,
  },
  {
    id: 23,
    name: "Kristen Phillips",
    company: "INFOTRIPS",
    timing: "2021-02-06T07:17:28+05:30",
    location: "Gratton",
    head: "Josefina",
    category: "Armstrong",
    size: 117,
  },
  {
    id: 24,
    name: "Cote Watson",
    company: "EXOTERIC",
    timing: "2016-03-03T11:09:19+05:30",
    location: "Sanford",
    head: "Kane",
    category: "Pennington",
    size: 702,
  },
  {
    id: 25,
    name: "Sanchez Barker",
    company: "KAGE",
    timing: "2022-12-28T03:13:15+05:30",
    location: "Gwynn",
    head: "Bertha",
    category: "Cobb",
    size: 198,
  },
  {
    id: 26,
    name: "Beryl Whitley",
    company: "XYLAR",
    timing: "2023-01-03T06:53:28+05:30",
    location: "Floris",
    head: "Sue",
    category: "Wynn",
    size: 489,
  },
  {
    id: 27,
    name: "Stella Morrow",
    company: "LIMAGE",
    timing: "2020-07-29T12:28:43+05:30",
    location: "Edmund",
    head: "Clarice",
    category: "Cabrera",
    size: 572,
  },
  {
    id: 28,
    name: "Spears Hutchinson",
    company: "EXOVENT",
    timing: "2017-07-28T09:10:41+05:30",
    location: "Selma",
    head: "Mcpherson",
    category: "Stephens",
    size: 989,
  },
  {
    id: 29,
    name: "Doyle Slater",
    company: "ACRODANCE",
    timing: "2015-03-30T09:30:08+05:30",
    location: "Shindler",
    head: "Dionne",
    category: "Barber",
    size: 715,
  },
];

export const categoryData = [
  {
    id: 0,
    category: "Humphrey",
  },
  {
    id: 1,
    category: "Avery",
  },
  {
    id: 2,
    category: "Langley",
  },
  {
    id: 3,
    category: "Chang",
  },
  {
    id: 4,
    category: "Matthews",
  },
  {
    id: 5,
    category: "Burris",
  },
  {
    id: 6,
    category: "Hoffman",
  },
  {
    id: 7,
    category: "Gilliam",
  },
  {
    id: 8,
    category: "Shepherd",
  },
  {
    id: 9,
    category: "Walters",
  },
  {
    id: 10,
    category: "Brooks",
  },
  {
    id: 11,
    category: "England",
  },
  {
    id: 12,
    category: "Torres",
  },
  {
    id: 13,
    category: "Walker",
  },
  {
    id: 14,
    category: "Castro",
  },
  {
    id: 15,
    category: "Fischer",
  },
  {
    id: 16,
    category: "Holmes",
  },
  {
    id: 17,
    category: "Eaton",
  },
  {
    id: 18,
    category: "Brock",
  },
  {
    id: 19,
    category: "Blake",
  },
  {
    id: 20,
    category: "Wilson",
  },
  {
    id: 21,
    category: "Delgado",
  },
  {
    id: 22,
    category: "Spence",
  },
  {
    id: 23,
    category: "Hall",
  },
  {
    id: 24,
    category: "Livingston",
  },
  {
    id: 25,
    category: "Hubbard",
  },
  {
    id: 26,
    category: "Boyd",
  },
  {
    id: 27,
    category: "Mullen",
  },
  {
    id: 28,
    category: "Stewart",
  },
  {
    id: 29,
    category: "Mercer",
  },
];
